### ISSUE TITLE
Convert to .smt2

### ISSUE THREAD

**Issue by tungvx** [hiwane/qeconv#7]
Hi there,

I am interested in your QE problems. Could you please provide the converter from .mpl to .smt2? I really want to test your problems with my SMT solver raSAT:  http://www.jaist.ac.jp/~mizuhito/tools/rasat.html.

Thanks in advanced!

**Comment by hiwane** [comment]
I have added `-t smt2` option in the `smt2` branch.
Is it sufficient for your use?

**Comment by tungvx** [comment]
Thank you very much for replying.

I had a problem of running, I ran in two ways:
1. I followed the install instruction: installing golang and setting up GOPATH, execute follows:
      $go get github.com/hiwane/qeconv/qeconv
But when I ran: 
      $echo "x>0:" | qeconv
I had the error "qeconv: command not found"

2. I ran in second way: I installed golang, then I checkout to smt2 branch:
     $git checkout -b smt2 origin/smt2
then, I ran:
     $go run qeconv/qeconv.go -t smt2 -i angle_bisector.mpl -o angle_bisector.smt2
and I got the error: 
      # command-line-arguments
      qeconv/qeconv.go:43: too many arguments in call to qeconv.ToSyn
      qeconv/qeconv.go:53: undefined: qeconv.ToSmt2

Could you please instruct me how to run because I am a newbie to golang.

**Comment by hiwane** [comment]
Could you try the following steps?

```sh
> go get github.com/hiwane/qeconv/qeconv
> cd ${GOPATH}/src/github.com/hiwane/qeconv/
> git checkout smt2
Branch smt2 set up to track remote branch smt2 from origin.
Switched to a new branch 'smt2'
> go get github.com/hiwane/qeconv/qeconv
> ${GOPATH}/bin/qeconv -h
Usage of /tmp/go/bin/qeconv:
  -f="syn": from {syn}
  -i="": input file
  -o="": output file
  -s=false: dup
  -t="syn": to {tex|math|qep|red|syn|smt2}
```

**Comment by tungvx** [comment]
When I ran:
```
go get github.com/hiwane/qeconv/qeconv
```
nothing is fetched into my ${GOPATH} folder. If I ran:
```
git clone git@github.com:hiwane/qeconv.git
cd qeconv/qeconv/
go install
./qeconv -h
```
then it works well, the output is:
```
Usage of ./qeconv:
  -f="syn": from {syn}
  -i="": input file
  -o="": output file
  -t="syn": to {math|tex|qep|red|syn}
```

But if I ran:
```
git clone git@github.com:hiwane/qeconv.git
cd qeconv/
git checkout smt2
cd qeconv
go install
```
there is the error:
```
# _/home/tungvx/go/src/github.com/hiwane/qeconv/qeconv
./qeconv.go:43: too many arguments in call to qeconv.ToSyn
./qeconv.go:53: undefined: qeconv.ToSmt2
```

Did you forget to push some changes to github?

**Comment by hiwane** [comment]
> Did you forget to push some changes to github?

No. I checked it on another PC.  You will find `smt2cnv.go`.

> 
```
cd qeconv
go install
```

Your operation is invalid.
`go` command searches "*.go" files from ${GOPATH}.


> nothing is fetched into my ${GOPATH} folder. So the output of:

I think this is not a problem of my repository but that of your `golang` environment.

Can you install another golang plugin by `go get`?   For example, https://github.com/peco/peco

**Comment by hiwane** [comment]
Here is an output:
```smt2
;##################################
; FILE     : angle_bisector.mpl
; AUTHOR   : H. Iwane <iwane@jp.fujitsu.com>
; CITATION : toy
; DOMAIN   : reals
; SyNRAC-20140624: solved
;##################################
; A(0, 0)、B(1,0)、C(-1, sqrt(3)) に対して、
; 三角形 ABCの２等分線 (mx) x + (my) y = mz
; (mx, my, mz は係数) とBC の交点D(Dx, Dy) の座標を求めよ

(((exists (k) 
(and (exists (C1) 
(and (exists (C0) 
(and (exists (mx my) 
(and (exists (mz) 
(and 
(and (not (= 0 (- (* (- 0 C0) (- 0 C1)) (* (- 0 C1) (- 1 C0))))) ; A,B,C が colinear でない
(and (not (= my 0)) (= ; 角の２等分線 (mx)x + (my)y = mz が y軸と平行でない
0 (- (* 1 (- 0 (/ mz my))) (* (- (/ (- mz mx) my) (/ mz my)) 0))) (= ; 角の２等分線が B を通る
; 角の２等分線が BC を AB : AC に内分する点(つまり D)を通る
0 (- (* 1 (- (+ (* (/ 1 (+ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) 1)) C1) (* (/ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) (+ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) 1)) 0)) (/ mz my))) (* (- (/ (- mz mx) my) (/ mz my)) (- (+ (* (/ 1 (+ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) 1)) C0) (* (/ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) (+ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) 1)) 1)) 0)))))) ;,

(or (and (exists (k1) 
(and (= (+ (* k 1) (* (- 1 k) C0)) (+ (* k1 0) (* (- 1 k1) 1))) (= 
(+ (* k 0) (* (- 1 k) C1)) (+ (* k1 (/ mz my)) (* (- 1 k1) (/ (- mz mx) my)))))) 
(not (= my 0))) 
(and (exists (k0) 
(and (= (+ (* k 1) (* (- 1 k) C0)) (+ (* k0 (/ mz mx)) (* (- 1 k0) (/ mz mx)))) (= 
(+ (* k 0) (* (- 1 k) C1)) (+ (* k0 0) (* (- 1 k0) 1))))) (= 
my 0))))) 

(or (not (= mx 0)) 
(not (= my 0))))) 
(and (= C0 -1) (= 
C1 (^ 3 (/ 1 2)))) (= 
Dx (+ (* k 1) (* (- 1 k) C0))))) (= 
Dy (+ (* k 0) (* (- 1 k) C1))))) (<= 
0 k) (<= 
k 1))) 
(and (< -Dy 0) (= (- (* 3 Dx) 1) 0) (= (- (* 3 (^ Dy 2)) 1) 0))) 
((exists (k C1 C0 mx my mz k1 k0) 
(and (and (and (and (and 
(and (not (= 0 (- (* (- 0 C0) (- 0 C1)) (* (- 0 C1) (- 1 C0))))) 
(and (not (= my 0)) (= 
0 (- (* 1 (- 0 (/ mz my))) (* (- (/ (- mz mx) my) (/ mz my)) 0))) (= 
0 (- (* 1 (- (+ (* (/ 1 (+ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) 1)) C1) (* (/ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) (+ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) 1)) 0)) (/ mz my))) (* (- (/ (- mz mx) my) (/ mz my)) (- (+ (* (/ 1 (+ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) 1)) C0) (* (/ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) (+ (^ (+ (^ (- 0 C0) 2) (^ (- 0 C1) 2)) (/ 1 2)) 1)) 1)) 0)))))) ;,

(or (and (and (= (+ (* k 1) (* (- 1 k) C0)) (+ (* k1 0) (* (- 1 k1) 1))) (= 
(+ (* k 0) (* (- 1 k) C1)) (+ (* k1 (/ mz my)) (* (- 1 k1) (/ (- mz mx) my))))) 
(not (= my 0))) 
(and (and (= (+ (* k 1) (* (- 1 k) C0)) (+ (* k0 (/ mz mx)) (* (- 1 k0) (/ mz mx)))) (= 
(+ (* k 0) (* (- 1 k) C1)) (+ (* k0 0) (* (- 1 k0) 1)))) (= 
my 0)))) 
(or (not (= mx 0)) 
(not (= my 0)))) 
(and (= C0 -1) (= 
C1 (^ 3 (/ 1 2)))) (= 
Dx (+ (* k 1) (* (- 1 k) C0)))) (= 
Dy (+ (* k 0) (* (- 1 k) C1)))) (<= 
0 k) (<= 
k 1))) 
(and (< -Dy 0) (= (- (* 3 Dx) 1) 0) (= (- (* 3 (^ Dy 2)) 1) 0))))
```

**Comment by tungvx** [comment]
You're right, my golang environment has problems. I re-installed it and now it works.

Could you please slightly modify the output of the converter to match the smt2 syntax? Suppose .mpl has the following format: ```[[a1, b1], [a2, b2], ...]:```. There are two possible output files for .smt2 over reals: one for the quantified formulas and another for the quantifier-free formulas:
1. The quantified formulas:
````
(set-logic NRA)
(set-info : optional information)
(declare-fun var1 () Real)
(declare-fun var2 () Real)
.....
(assert (a1'))
(assert (a2'))
....
(check-sat)
````
where ```a1', a2',...``` are the transformed formulas of ```a1, a2,...``` as currently in your converter. Please note that because .smt2 for real numbers does not has ```^``` and ```-``` unary function symbols, ``` (^ a2 2)``` and ```- a1`` should be ``` (* a2 a2)```and  ```- 0 a1``` resp.
2. The quantifier-free formulas:
````
(set-logic QF_NRA)
(set-info : optional information)
(declare-fun var1 () Real)
(declare-fun var2 () Real)
....
(assert (b1'))
(assert (b2'))
....
(check-sat)
````
where ```b1', b2',...``` are the transformed formulas of ```b1, b2,...``` as currently in your converter.

Could you please separate and add options for generating these two kinds of outputs? 
Here is an example of the two outputs. If the .mpl file is 
````
###################################
# FILE     : nagoya1999-Ri-1-2.mpl
# AUTHOR   : H. Iwane <iwane@jp.fujitsu.com>
# DOMAIN   : reals
# CITATION : first entrance exam Nagoya U. 1999, science [1](2)
###################################


[[
All([p1,p2], And(
  a1^2 + a2^2 = 1, # (1)
  (a1*p1+a2*p2)^2 +
  (b1*p1+b2*p2)^2 =
  p1^2 + p2^2)),
  And(Or(And(a1^2+a2^2=1,b1=a2,b2=-a1),
         And(a1^2+a2^2=1,b1=-a2,b2=a1)))]]:
````
the current output is
```
;##################################
; FILE     : nagoya1999-Ri-1-2.mpl
; AUTHOR   : H. Iwane <iwane@jp.fujitsu.com>
; DOMAIN   : reals
; CITATION : first entrance exam Nagoya U. 1999, science [1](2)
;##################################


((
(forall (p1 p2) (and (= 
(+ (^ a1 2) (^ a2 2)) 1) (= ; (1)
(+ (^ (+ (* a1 p1) (* a2 p2)) 2) 
(^ (+ (* b1 p1) (* b2 p2)) 2)) 
(+ (^ p1 2) (^ p2 2))))) 
(or (and (= (+ (^ a1 2) (^ a2 2)) 1) (= b1 a2) (= b2 -a1)) 
(and (= (+ (^ a1 2) (^ a2 2)) 1) (= b1 -a2) (= b2 a1)))))
```
and the .smt2 for quantified formulas should be:
```
(set-logic NRA)
(set-info :source | 
FILE: nagoya1999-Ri-1-2.mpl 
AUTHOR: H. Iwane <iwane@jp.fujitsu.com> 
CITATION: first entrance exam Nagoya U. 1999, science [1](2) 
|)
(declare-fun a1 () Real)
(declare-fun a2 () Real)
(declare-fun b1 () Real)
(declare-fun b2 () Real)
(assert (forall ((p1 Real) (p2 Real)) (and (= 
(+ (* a1 a1) (* a2 a2)) 1) (=
(+ (* (+ (* a1 p1) (* a2 p2)) (+ (* a1 p1) (* a2 p2))) 
(^ (+ (* b1 p1) (* b2 p2)) 2)) 
(+ (* p1 p1) (* p2 p2))))))
(check-sat)
```
and the .smt2 for quantifier-free formulas should be:
```
(set-logic QF_NRA)
(set-info :source | 
FILE: nagoya1999-Ri-1-2.mpl
AUTHOR: H. Iwane <iwane@jp.fujitsu.com>
CITATION: first entrance exam Nagoya U. 1999, science [1](2) 
|)
(declare-fun a1 () Real)
(declare-fun a2 () Real)
(declare-fun b1 () Real)
(declare-fun b2 () Real)
(assert (or (and (= (+ (* a1 a1) (* a2 a2)) 1) (= b1 a2) (= b2 (- 0 a1))) (and (= (+ (* a1 a1) (* a2 a2)) 1) (= b1 (- 0 a2)) (= b2 a1))))
(check-sat)
```

**Comment by hiwane** [comment]
> Could you please separate and add options for generating these two kinds of outputs?
Here is an example of the two outputs. If the .mpl file is

Ok. I understand.
Please let me know the followings:

- Is `(* x1 x2 x3 x4)` valid?
- Do `smt2` and `raSAT` support `abs()`, rational functions and rational exponential?

**Comment by tungvx** [comment]
According to the smt2 tutorial (http://www.grammatech.com/resource/smt/SMTLIBTutorial.pdf)
> Is (* x1 x2 x3 x4) valid?

Yes, "real binary operations" are "left associative" (page 25)

>Do smt2 and raSAT support abs(), rational functions and rational exponential?

In the theory of reals numbers, smt2 standard defines (page 58):
```
The Reals theory contains the following:
• a sort Real
• both <numeral>s and <decimal>s are typed as Real
• the expected + - * / functions
• the expected > < >= <= comparison functions, returning Bool
```
So in smt2 standard, ```abs()``` and ```rational exponential``` are not allowed, whilst rational function is. Although raSAT currently does not support rational function, please use it in your converter because other SMT solvers can process it ^_^. We will support that function in the future.

**Comment by hiwane** [comment]
I have added `-n` option. Could you check it?
- you can obtain the number of fof by `qeconv -n -1 -i {file}`
- if fof has `abs()` or rational exponential, `qeconv` returns an error.
- We will add first-order formulas without `abs()` and `rational exp.` to https://github.com/hiwane/qe_problems.

**Comment by tungvx** [comment]
I ran ```qeconv -n -1 -i {file}``` the number of fof is displayed. 

> if fof has abs() or rational exponential, qeconv returns an error.

I ran ```${GOPATH}/bin/qeconv -t smt2 -i redlog.mpl -n 0```, I got the message ```unsupported input```, ```redlog.mpl``` does not contain ```abs()``` or rational exponential?:
```
###################################
# FILE     : redlog.mpl
# AUTHOR   : H. Iwane <iwane@jp.fujitsu.com>
# CITATION : http://www.redlog.eu/
# DOMAIN   : reals
# RELATED  : qebook p.53 example 1.12
###################################

[[
  All([x], Ex([y], And(x^2+x*y+b > 0, x+a*y^2+b <= 0))),
  And(a<0,b>0)
]]:
```

**Comment by hiwane** [comment]
Sorry.
`-n 0` (default) means that `qeconv` uses all formulas, and thus `-n 0` is not supported for `smt2`.

```
> qeconv -i redlog.mpl -n 0
###################################
# FILE     : redlog.mpl
# AUTHOR   : H. Iwane <iwane@jp.fujitsu.com>
# CITATION : http://www.redlog.eu/
# DOMAIN   : reals
# RELATED  : qebook p.53 example 1.12
###################################

[[
All([x],Ex([y],And(0 < x^2+x*y+b,x+a*y^2+b <= 0))),
And(a < 0,0 < b)]]:
> qeconv -i redlog.mpl -n 1

All([x],Ex([y],And(0 < x^2+x*y+b,x+a*y^2+b <= 0))):
> qeconv -i redlog.mpl -n 2

And(a < 0,0 < b):
```

**Comment by tungvx** [comment]
Thank you very much, now I can run it. Some small points:

*  In the smt2 output, ```set logic`` should be ```set-logic```.
*  Can you change current ```NRA``` to ```QF_NRA``` and vice versa. For example, if I run: ```${GOPATH}/bin/qeconv -t smt2 -i hokudai1999-Bun-2-3-m.mpl -n 1```, the output is:
```
(set logic QF_NRA)
(declare-fun S () Real)
(assert 
(exists ( (a Real) ) (and (= S (+ (* (/ (- 0 1) 3) (* a a a)) (* (/ 1 3) a))) (< 0 a) (< a 1)) ))
(check-sat)
```
but the first line should be:  ```(set-logic NRA)``` because the formula here is quantified not quantifier-free.
* I have a question. In one .mpl file, there is a list: ```[[a1, b1], [a2, b2], ...]```, what is the relationship between ```a1, a2,...```. I mean can I consider each file to represent the formula: ```a1 \wedge a2 \wedge ...```?

**Comment by hiwane** [comment]
Thank you for your reply. I fixed the `set-logic` problem.

> I have a question. In one .mpl file, there is a list

They have no relation.

For example,  the formulas in https://github.com/hiwane/qe_problems/blob/master/problems/paper/chen14.mpl are derived from same paper, but have no relation.

**Comment by tungvx** [comment]
Anyway, why should you have extra endlines after assert command:
```
${GOPATH}/bin/qeconv -t smt2 -n 2 -i hokudai1999-Bun-2-3-m.mpl 
(set-logic QF_NRA)
(declare-fun S () Real)
(assert 







(and (<= (* 243 (* S S)) 4) (< (- 0 S) 0)))

```
In the tutorial http://www.grammatech.com/resource/smt/SMTLIBTutorial.pdf, all the command should be in one line ^_^, that means:
```
(set-logic QF_NRA)
(declare-fun S () Real)
(assert (and (<= (* 243 (* S S)) 4) (< (- 0 S) 0)))
```

**Comment by hiwane** [comment]
Thanx. I fixed it.

- https://github.com/hiwane/qeconv/commit/348d6a5705ea8991f90b88c80df2439230d48d8d this commit is valid?
    - for `And(x>0, y>0)`, `qeconv` outputs
```
(set-logic QF_NRA)
(declare-fun x () Real)
(declare-fun y () Real)
(assert (< 0 x))
(assert (< 0 y))
(check-sat)
```

> and the .smt2 for quantified formulas should be:
```
(set-logic NRA)
```

Is `NRA` a valid theory name? For the following file, `z3` outputs  warning message `WARNING: unknown logic, ignoring set-logic command`:
```
(set-logic NRA)
(declare-fun b () Real)
(declare-fun c () Real)
(assert (exists ( (x Real) ) (= (+ (+ (* x x) (* b x)) c) 0) ))
(check-sat)
```

**Comment by tungvx** [comment]
> 348d6a5 this commit is valid?

Yes, it is valid.

>Is NRA a valid theory name?

Yes, it is. Based on the benchmarks from http://smt-lib.org/, we have the theory NRA, and here is an example:
```
(set-logic NRA)
(set-info :source |
These benchmarks used in the paper:

  Dejan Jovanovic and Leonardo de Moura.  Solving Non-Linear Arithmetic.
  In IJCAR 2012, published as LNCS volume 7364, pp. 339--354.

The keymaera family contains VCs from Keymaera verification, see:

  A. Platzer, J.-D. Quesel, and P. Rummer.  Real world verification.
  In CADE 2009, pages 485-501. Springer, 2009.

Submitted by Dejan Jovanovic for SMT-LIB.

 KeYmaera example: accelerating, node 2100 For more info see: @see @see "Andre Platzer and Jan-David Quesel. European Train Control System: A case study in formal verification. In Karin Breitman and Ana Cavalcanti, editors, 11th International Conference on Formal Engineering Methods, ICFEM, Rio de Janeiro, Brasil, Proceedings, volume 5885 of LNCS, pages 246-265. Springer, 2009." 
|)
(set-info :smt-lib-version 2.0)
(set-info :category "industrial")
(set-info :status unsat)
(declare-fun v () Real)
(declare-fun b () Real)
(declare-fun vuscore2dollarskuscore0 () Real)
(declare-fun A () Real)
(declare-fun ts2uscore0 () Real)
(declare-fun ep () Real)
(declare-fun m () Real)
(declare-fun zuscore2dollarskuscore0 () Real)
(declare-fun t2uscore0dollarskuscore0 () Real)
(declare-fun z () Real)
(assert (not (exists ((ts2uscore0 Real)) (let ((?v_1 (* 2 b)) (?v_0 (* vuscore2dollarskuscore0 vuscore2dollarskuscore0)) (?v_2 (- m zuscore2dollarskuscore0)) (?v_3 (+ (* A t2uscore0dollarskuscore0) vuscore2dollarskuscore0))) (=> (and (and (and (and (and (and (=> (and (<= 0 ts2uscore0) (<= ts2uscore0 t2uscore0dollarskuscore0)) (and (>= (+ (* A ts2uscore0) vuscore2dollarskuscore0) 0) (<= ts2uscore0 ep))) (>= t2uscore0dollarskuscore0 0)) (>= ?v_2 (+ (/ ?v_0 ?v_1) (* (+ (/ A b) 1) (+ (* (/ A 2) (* ep ep)) (* ep vuscore2dollarskuscore0)))))) (<= ?v_0 (* ?v_1 ?v_2))) (<= (* v v) (* ?v_1 (- m z)))) (> b 0)) (>= A 0)) (<= (* ?v_3 ?v_3) (* ?v_1 (- m (* (/ 1 2) (+ (+ (* A (* t2uscore0dollarskuscore0 t2uscore0dollarskuscore0)) (* (* 2 t2uscore0dollarskuscore0) vuscore2dollarskuscore0)) (* 2 zuscore2dollarskuscore0)))))))))))
(check-sat)
(exit)
```

**Comment by hiwane** [comment]
Thank you for the reply. Can I close this issue?

**Comment by tungvx** [comment]
I think we can close the issue. Thank you very much for providing the feature of smt2 :).

**Comment by hiwane** [comment]
I have merged the smt2 branch into the master branch. 

Ogawa Sensei ni Yoroshiku Otsutae Kudasai :-)

**Comment by tungvx** [comment]
どうもありがとうございました。小川先生をしっていますか。先生に伝えます。^_^.
